### ISSUE TITLE
Unable to setup

### ISSUE THREAD

**Issue by qery** [jaroschek/home-assistant-eaton-ups#17] opened 2024-05-24 13:55 UTC
I'm unable to setup new device - "There is no current event loop in thread 'SyncWorker_*'. After entering all informations, the setup is not able to start device.

![image](https://github.com/jaroschek/home-assistant-eaton-ups/assets/2520114/dddc4f81-b298-4fea-810a-fd152ed41d8e)

Log:
[home-assistant_eaton_ups_2024-05-24T13-46-37.475Z.log](https://github.com/jaroschek/home-assistant-eaton-ups/files/15435346/home-assistant_eaton_ups_2024-05-24T13-46-37.475Z.log)

Looks like the integration is not able to read snmp data, but when I try to read them with SnmpGet I can read all of the OIDs in log.

![image](https://github.com/jaroschek/home-assistant-eaton-ups/assets/2520114/e7e1b2fc-2bb2-4dbe-8a3a-2159eb90f5d8)

Edit: I tried SNMPv1 and also SNMPv3, with/without password etc...

**Comment by jonatino** [comment] 2024-06-07 06:26
Also have the same errors. I have an eaton 9130 that only works with snmp v1

**Comment by fwg1000** [comment] 2024-06-15 14:18
Same here (HA 2024.6.2)

![15-06-_2024_16-08-19](https://github.com/jaroschek/home-assistant-eaton-ups/assets/165693188/4601a4fa-ad4b-4bbe-b660-bbee2a79837f)

**Comment by jaroschek** [comment] 2024-09-18 15:12
@fwg1000 @qery @jonatino I have recently updated the used PySNMP library to the same version 6.2.5 that Home Assistant is using for the core SNMP component. So you could try the current release: https://github.com/jaroschek/home-assistant-eaton-ups/releases/tag/1.2.0

If you have still problems, you can also try the latest pre-release: https://github.com/jaroschek/home-assistant-eaton-ups/releases/tag/1.2.1-beta1

There I'm currently testing a change that should resolve problems caused by missing OIDs in different models by ignoring them.

**Comment by jaroschek** [comment] 2024-10-28 10:59
I close this issue, as there was no feedback for over a month and similar issues could be solved.

**Closed by jaroschek** 2024-10-28 10:59 UTC
